### ISSUE TITLE
elements.lists.scss not needed (yet)

### ISSUE THREAD

**Issue by bjoernsteinborn** [WebDevLuke/OrionCSS#1]
...as dd, ol and ul elements have already a margin reset in generic.reset.scss

**Comment by WebDevLuke** [comment]
Nice spot! It's a holdover from a much older version which I just failed to remove. I'll remove it in the next patch. 👍

**Comment by WebDevLuke** [comment]
Fixed as of [v2.2.1](https://github.com/WebDevLuke/OrionCSS/releases/tag/v2.2.1).
