### ISSUE TITLE
Empty error output of spacing()

### ISSUE THREAD

**Issue by bjoernsteinborn** [WebDevLuke/OrionCSS#2]
@error `#{$chosen-spacing}` doesn't exist in 'settings.colors'"

has to be:
@error `#{$value}` doesn't exist in 'settings.colors'"

**Comment by WebDevLuke** [comment]
Nice spot.

**Comment by WebDevLuke** [comment]
Fixed as of [v2.2.2](https://github.com/WebDevLuke/OrionCSS/releases/tag/v2.2.2)
